spring:
  main:
    allow-circular-references: true #allowing beans to have circular references.
  profiles:
    active: dev #Active DEV or PRO Environment

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        jdbc.time_zone: GMT+7

    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: phuocduc2k3@gmail.com
    password: rpfrhdvdmqropojm
    properties:
      mail:
        mime:
          charset=UTF-8: true
        smtp:
          auth: true
          starttls.enable: true


application:
  security:
    jwt:
      secret-key: +yWcUBR+6S/qFsT5WNV7sN8v+md0o68L72mTZkmyBxOssvaZxXNBb5jakzlXIXGYgYBLvqLpXNgH1uQAPB71DQ==
      expiration:
        access: 20000 # a day
        refresh: 604800000 # 7 days

# Firebase
url:
  firebase:
    bucket: job-worked.appspot.com
    folder: https://firebasestorage.googleapis.com/v0/b/

#swagger custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

  #swagger url: http://host/context-path/swagger-ui/index.html
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  tomcat:
    uri-encoding: UTF-8