server:
  port: 10280
  address: 0.0.0.0


db:
  port: 3306
  name: dream_x_work
  endpoint: 34.87.10.95
  username: root
  password: Ducvc123123!@#$%
  connection-name: algebraic-rider-410613:asia-southeast1:dreamxwork

spring:
  datasource:
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
  cloud:
    gcp:
      sql:
        instance-connection-name: ${db.connection-name}
        database-name: ${db.name}


domain:
  path: https://job-finder-be-production.up.railway.app
  #https://springboot-dreamxwork.et.r.appspot.com/

url:
  server:
    path:  ${domain.path}
  client:
    path: http://localhost:3000/