server:
  port: 8080
db:
  port: 3306
  name: job_finder
  endpoint: localhost
  username: root
  password: Ducvc123123!@#$%

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}

url:
  server:
    path:  http://localhost:8080
  client:
    path: http://localhost:3000/