spring:
  main:
    allow-circular-references: true #allowing beans to have circular references.

  profiles:
    active: pro #Active DEV or PRO Environment
  jackson:
    time-zone: GMT+7
    serialization:
      fail-on-empty-beans: false

  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        jdbc.time_zone: GMT+7
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: phuocduc2k3@gmail.com
    password: rpfrhdvdmqropojm
    properties:
      mail:
        mime:
          charset=UTF-8:
        smtp:
          auth: true
          starttls.enable: true



application:
  security:
    jwt:
      secret-key: kiGtJXhv5R86NBx8gS7kO9TRq6XKP5Pzs44cEpgAzNA=
      expiration: 20000 # a day
      refresh:
        expiration: 604800000 # 7 days



